# Generated by Django 2.1.3 on 2018-12-03 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('medio_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cajas.FormaPago')),
            ],
        ),
        migrations.RemoveField(
            model_name='venta',
            name='forma_pago',
        ),
        migrations.AlterField(
            model_name='venta',
            name='factura',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cajas.Venta'),
        ),
    ]
