# Generated by Django 2.1.3 on 2018-12-04 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_auto_20181130_0032'),
        ('cajas', '0002_auto_20181203_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='orden_de_trabajo',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='precio',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='servicios.DetalleOrdenDeTrabajo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
    ]
