# Generated by Django 2.1.3 on 2018-12-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0003_auto_20181204_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='comprobante_numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
