# Generated by Django 2.1.3 on 2018-12-05 19:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('cajas', '0004_pago_comprobante_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleRecibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='PagoRecibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprobante_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('monto', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('medio_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cajas.FormaPago')),
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('monto', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente')),
                ('sesion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='cajas.Sesion')),
            ],
        ),
        migrations.RenameModel(
            old_name='Pago',
            new_name='PagoVenta',
        ),
        migrations.AddField(
            model_name='venta',
            name='pagado',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='pagorecibo',
            name='recibo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cajas.Recibo'),
        ),
        migrations.AddField(
            model_name='detallerecibo',
            name='recibo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cajas.Recibo'),
        ),
        migrations.AddField(
            model_name='detallerecibo',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cajas.Venta'),
        ),
    ]
