# Generated by Django 2.1.3 on 2018-12-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0005_auto_20181205_1602'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PagoVenta',
            new_name='Pago',
        ),
        migrations.RemoveField(
            model_name='detallerecibo',
            name='recibo',
        ),
        migrations.RemoveField(
            model_name='detallerecibo',
            name='venta',
        ),
        migrations.RemoveField(
            model_name='pagorecibo',
            name='medio_de_pago',
        ),
        migrations.RemoveField(
            model_name='pagorecibo',
            name='recibo',
        ),
        migrations.RemoveField(
            model_name='recibo',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='recibo',
            name='sesion',
        ),
        migrations.AlterField(
            model_name='venta',
            name='pagado',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=15),
        ),
        migrations.DeleteModel(
            name='DetalleRecibo',
        ),
        migrations.DeleteModel(
            name='PagoRecibo',
        ),
        migrations.DeleteModel(
            name='Recibo',
        ),
    ]
