# Generated by Django 2.1.3 on 2018-12-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0006_auto_20181207_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('PG', 'Pagado')], default='PE', max_length=2, verbose_name='Estado de Pago'),
        ),
    ]
