# Generated by Django 2.1.3 on 2018-12-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0007_venta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('PG', 'Pagado')], default='PE', editable=False, max_length=2, verbose_name='Estado de Pago'),
        ),
    ]
