# Generated by Django 2.1.3 on 2019-05-25 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20190307_2210'),
        ('cajas', '0008_auto_20181212_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='dato_facturacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.DatoFacturacion'),
        ),
    ]
