# Generated by Django 2.1.3 on 2018-11-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150, verbose_name='descripción')),
                ('categoria', models.CharField(choices=[('pel', 'Peluquería'), ('spa', 'Spa')], default='pel', max_length=3)),
                ('precio', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('activo', models.BooleanField(default=True, editable=False)),
            ],
        ),
    ]
