# Generated by Django 2.1.3 on 2018-11-29 16:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOrdenDeTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='OrdenDeTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha y hora de creación')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('facturado', models.BooleanField(default=False, editable=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente')),
                ('creado_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de trabajo',
                'verbose_name_plural': 'Ordenes de trabajo',
            },
        ),
        migrations.AddField(
            model_name='detalleordendetrabajo',
            name='orden_de_trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.OrdenDeTrabajo'),
        ),
        migrations.AddField(
            model_name='detalleordendetrabajo',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.Servicio'),
        ),
    ]
