# Generated by Django 2.1.3 on 2018-11-30 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20181129_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendetrabajo',
            name='creacion',
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='fecha',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='hora',
            field=models.TimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
