# Generated by Django 2.1.3 on 2018-12-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_auto_20181130_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendetrabajo',
            name='facturado',
        ),
        migrations.AddField(
            model_name='detalleordendetrabajo',
            name='facturado',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='estado_facturacion',
            field=models.CharField(choices=[('no', 'No facturado'), ('pa', 'Facturado Parcialmente'), ('si', 'Facturado Totalmente')], default='no', max_length=2),
        ),
    ]
