# Generated by Django 2.1.3 on 2018-12-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_auto_20181204_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='estado_facturacion',
            field=models.CharField(choices=[('no', 'No facturado'), ('pa', 'Facturado Parcialmente'), ('si', 'Facturado Totalmente')], default='no', editable=False, max_length=2),
        ),
    ]
