# Generated by Django 2.1.3 on 2020-05-21 14:36

from django.db import migrations, models
import servicios.models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_auto_20181205_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordendetrabajo',
            options={'verbose_name': 'Sesión', 'verbose_name_plural': 'Sesiones'},
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to=servicios.models.get_file_path),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='comentarios',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
