# Generated by Django 2.1.3 on 2021-01-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_auto_20200521_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordendetrabajo',
            options={'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(choices=[('CA1', 'Categoría 1'), ('CA2', 'Categoría 2')], default='CA1', max_length=3),
        ),
    ]
