# Generated by Django 2.1.3 on 2021-02-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_auto_20210223_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='motivo_de_consulta',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
