# Generated by Django 2.1.3 on 2021-07-16 19:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleTurno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.Servicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('hora_inicio', models.TimeField(default=datetime.datetime.now)),
                ('hora_finalizacion', models.TimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('pv', 'Primera'), ('co', 'Control')], default='pv', max_length=2)),
                ('box', models.CharField(blank=True, choices=[('box_27', 'Extra 1'), ('box_28', 'Extra 2'), ('box_29', 'Extra 3'), ('box_30', 'Extra 4'), ('box_31', 'Extra 5')], max_length=6, null=True, verbose_name='Profesional')),
                ('especialidad', models.CharField(choices=[('EXT', 'Extra')], max_length=3)),
                ('repeticiones', models.IntegerField(blank=True, default=0, null=True, verbose_name='Repeticiones semanales')),
                ('cancelado', models.BooleanField(default=False, editable=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente', verbose_name='Paciente')),
            ],
        ),
        migrations.AddField(
            model_name='detalleturno',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.Turno'),
        ),
    ]
