# Generated by Django 2.1.3 on 2018-12-03 16:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicios', '0003_auto_20181130_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleTurno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.Servicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('hora_inicio', models.TimeField(default=datetime.datetime.now)),
                ('hora_finalizacion', models.TimeField(blank=True, null=True)),
                ('cateogoria', models.CharField(choices=[('pel', 'Peluquería'), ('spa', 'Spa')], default='pel', max_length=3)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='detalleturno',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.Turno'),
        ),
    ]
