# Generated by Django 2.1.3 on 2018-12-11 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='cateogoria',
            new_name='categoria',
        ),
    ]
