# Generated by Django 2.1.3 on 2019-09-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0005_turno_repeticiones'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='box',
            field=models.CharField(blank=True, choices=[('hel_1', 'Helen 1'), ('hel_2', 'Helen 2'), ('raq_1', 'Raquel 1'), ('raq_2', 'Raquel 2'), ('mir_1', 'Mirtha 1'), ('mir_2', 'Mirtha 2'), ('san_1', 'Sanie 1'), ('san_2', 'Sanie 2'), ('aud_1', 'Auda 1'), ('aud_2', 'Auda 2'), ('nutri', 'Nutrición'), ('pel_1', 'Peluquería 1'), ('pel_2', 'Peluquería 2'), ('manic', 'Manicura')], max_length=5, null=True),
        ),
    ]
