# Generated by Django 2.1.3 on 2021-01-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0007_auto_20190923_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='responsable',
        ),
        migrations.AlterField(
            model_name='turno',
            name='box',
            field=models.CharField(blank=True, choices=[('box_1', 'BOX 1'), ('box_2', 'BOX 2'), ('box_3', 'BOX 3'), ('box_4', 'BOX 4'), ('box_5', 'BOX 5')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='categoria',
            field=models.CharField(choices=[('pel', 'Peluquería'), ('spa', 'Spa')], default='pel', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='turno',
            name='repeticiones',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Repeticiones semanales'),
        ),
    ]
