# Generated by Django 2.1.3 on 2021-01-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0008_auto_20210118_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='categoria',
        ),
    ]
