# Generated by Django 2.1.3 on 2021-02-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0009_remove_turno_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='especialidad',
            field=models.CharField(choices=[('M3R', 'Programa 3R - MASQUELIER'), ('NUT', 'Nutrición'), ('S3R', 'Programa 3R - SAGA'), ('PED', 'Pediatría'), ('PSI', 'Psicología')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
