# Generated by Django 2.1.3 on 2021-05-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0013_auto_20210510_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='tipo',
            field=models.CharField(choices=[('pv', 'Primera'), ('co', 'Control')], default='pv', max_length=2),
        ),
        migrations.AlterField(
            model_name='turno',
            name='repeticiones',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Repeticiones semanales'),
        ),
    ]
