# Generated by Django 2.1.3 on 2021-05-17 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0015_auto_20210511_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente', verbose_name='Paciente'),
        ),
    ]
