# Generated by Django 2.1.3 on 2018-11-29 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre y Apellido')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='teléfono')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='dirección')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='e-mail')),
                ('puntos_acumulados', models.IntegerField(default=0, verbose_name='Puntos acumulados')),
            ],
        ),
        migrations.CreateModel(
            name='DatoFacturacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=100, verbose_name='Razón Social')),
                ('ruc', models.CharField(max_length=30, verbose_name='RUC')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
            ],
            options={
                'verbose_name': 'Dato de facturación',
                'verbose_name_plural': 'Datos de facturación',
            },
        ),
    ]
