# Generated by Django 2.1.3 on 2021-02-21 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20210221_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cansacio_o_fatiga',
            new_name='cansancio_o_fatiga',
        ),
    ]
