# Generated by Django 2.1.3 on 2021-02-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20210223_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='acides_estomacal',
            field=models.BooleanField(default=False, verbose_name='acidez estomacal'),
        ),
    ]
